# Generated by Django 3.0.6 on 2020-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('exid', models.BigAutoField(db_column='exId', primary_key=True, serialize=False)),
                ('exidname', models.CharField(db_column='exIdName', max_length=30)),
                ('type', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'experiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geneexpression',
            fields=[
                ('geneid', models.BigAutoField(db_column='geneId', primary_key=True, serialize=False)),
                ('genename', models.CharField(db_column='geneName', max_length=30)),
                ('geneexpressionvalues', models.FloatField(db_column='geneExpressionValues')),
            ],
            options={
                'db_table': 'geneExpression',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geneset',
            fields=[
                ('genesetid', models.BigAutoField(db_column='genesetId', primary_key=True, serialize=False)),
                ('genesetname', models.CharField(db_column='genesetName', max_length=50)),
            ],
            options={
                'db_table': 'geneset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.BigAutoField(db_column='patientId', primary_key=True, serialize=False)),
                ('paidname', models.CharField(db_column='paIdName', max_length=30)),
                ('artype', models.CharField(db_column='arType', max_length=10)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
